
package view;

/**
 *
 * @author Acer
 */
public class admindashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(admindashboard.class.getName());
    public admindashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminDashboard = new javax.swing.JLabel();
        drawerPanel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        recentbookings = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        hotellabellogo = new javax.swing.JLabel();
        THREElines = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();
        Databaseconnected = new javax.swing.JLabel();
        GenerateInvoice = new javax.swing.JButton();
        admindashboardbackgroundcolor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        AdminDashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AdminDashboard.setForeground(new java.awt.Color(232, 128, 153));
        AdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboard.setText("Admin Dashboard");
        jPanel1.add(AdminDashboard);
        AdminDashboard.setBounds(700, 56, 340, 60);

        drawerPanel.setLayout(null);

        profile.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vector (3).png"))); // NOI18N
        profile.setText("     Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        drawerPanel.add(profile);
        profile.setBounds(20, 360, 190, 30);

        dashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        drawerPanel.add(dashboard);
        dashboard.setBounds(70, 210, 150, 30);

        recentbookings.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        recentbookings.setForeground(new java.awt.Color(255, 255, 255));
        recentbookings.setText("Recent Bookings");
        recentbookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recentbookingsMouseClicked(evt);
            }
        });
        drawerPanel.add(recentbookings);
        recentbookings.setBounds(70, 260, 220, 30);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        drawerPanel.add(bookingicon);
        bookingicon.setBounds(20, 260, 25, 30);

        support.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("Support");
        support.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supportMouseClicked(evt);
            }
        });
        drawerPanel.add(support);
        support.setBounds(70, 310, 160, 30);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        drawerPanel.add(dashboardicon);
        dashboardicon.setBounds(20, 210, 70, 30);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        drawerPanel.add(supporticon);
        supporticon.setBounds(20, 320, 50, 25);

        hotellabellogo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        hotellabellogo.setForeground(new java.awt.Color(89, 4, 20));
        hotellabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 3.png"))); // NOI18N
        hotellabellogo.setText("Hotel in a Tap");
        drawerPanel.add(hotellabellogo);
        hotellabellogo.setBounds(10, 620, 180, 70);

        THREElines.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\Hamburger Menu (1).png")); // NOI18N
        drawerPanel.add(THREElines);
        THREElines.setBounds(10, 10, 30, 40);

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel.png"))); // NOI18N
        panel.setMinimumSize(new java.awt.Dimension(363, 720));
        panel.setPreferredSize(new java.awt.Dimension(330, 700));
        drawerPanel.add(panel);
        panel.setBounds(0, 0, 330, 750);

        jPanel1.add(drawerPanel);
        drawerPanel.setBounds(100, 10, 330, 710);
        jPanel1.add(Databaseconnected);
        Databaseconnected.setBounds(650, 210, 410, 320);

        GenerateInvoice.setBackground(new java.awt.Color(184, 12, 47));
        GenerateInvoice.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        GenerateInvoice.setForeground(new java.awt.Color(232, 128, 153));
        GenerateInvoice.setText("Generate Invoice");
        GenerateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateInvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(GenerateInvoice);
        GenerateInvoice.setBounds(770, 560, 170, 40);

        admindashboardbackgroundcolor.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\Screenshot 2025-12-21 115223.png")); // NOI18N
        jPanel1.add(admindashboardbackgroundcolor);
        admindashboardbackgroundcolor.setBounds(0, 0, 1280, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
        this.dispose();

        // Open profile
        //new adminprofile().setVisible(true);
    }//GEN-LAST:event_profileMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        //        // TODO add your handling code here:
        //        this.dispose();
        //
        //        // Open dashboard
        //        new admindashboard().setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void recentbookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentbookingsMouseClicked
        ////        // TODO add your handling code here:
        ////        this.dispose();
        ////
        ////        //Open bookinghistory
        ////        new bookinghistory().setVisible(true);
    }//GEN-LAST:event_recentbookingsMouseClicked

    private void supportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportMouseClicked
        // TODO add your handling code here:
        //        this.dispose();
        //
        //        // Open support
        //        new support().setVisible(true);
    }//GEN-LAST:event_supportMouseClicked

    private void GenerateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new admindashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel Databaseconnected;
    private javax.swing.JButton GenerateInvoice;
    private javax.swing.JLabel THREElines;
    private javax.swing.JLabel admindashboardbackgroundcolor;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JPanel drawerPanel;
    private javax.swing.JLabel hotellabellogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel recentbookings;
    private javax.swing.JLabel support;
    private javax.swing.JLabel supporticon;
    // End of variables declaration//GEN-END:variables
}
