/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


/**
 *
 * @author sailenawale
 */
public class admindashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(admindashboard.class.getName());

    /**
     * Creates new form admindash
     */
    public admindashboard() {
        initComponents();
        drawerPanel.setLocation(-300, 0); // Start with drawer hidden
        new controller.AdminDashboardController().setupAdminDashboard(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminDashboard = new javax.swing.JLabel();
        GenerateInvoice = new javax.swing.JButton();
        slogan = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        menuicon = new javax.swing.JLabel();
        drawerPanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        recentbookings = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        hotelprofileicon = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        AdminDashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        AdminDashboard.setForeground(new java.awt.Color(232, 128, 153));
        AdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboard.setText("Admin Dashboard");
        jPanel1.add(AdminDashboard);
        AdminDashboard.setBounds(590, 40, 340, 60);

        GenerateInvoice.setBackground(new java.awt.Color(184, 12, 47));
        GenerateInvoice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        GenerateInvoice.setForeground(new java.awt.Color(232, 128, 153));
        GenerateInvoice.setText("Generate Invoice");
        GenerateInvoice.setBorder(null);
        jPanel1.add(GenerateInvoice);
        GenerateInvoice.setBounds(650, 620, 220, 40);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(100, 616, 90, 70);
        jPanel1.add(image);
        image.setBounds(430, 180, 410, 420);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 570, 100, 120);

        menuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hamburger Menu.png"))); // NOI18N
        menuicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuiconMouseClicked(evt);
            }
        });
        jPanel1.add(menuicon);
        menuicon.setBounds(10, 10, 50, 40);

        drawerPanel.setLayout(null);

        dashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        drawerPanel.add(dashboard);
        dashboard.setBounds(70, 210, 150, 30);

        recentbookings.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        recentbookings.setForeground(new java.awt.Color(255, 255, 255));
        recentbookings.setText("Recent Bookings");
        drawerPanel.add(recentbookings);
        recentbookings.setBounds(70, 260, 220, 30);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        drawerPanel.add(bookingicon);
        bookingicon.setBounds(20, 260, 25, 30);

        profile.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        drawerPanel.add(profile);
        profile.setBounds(70, 350, 160, 40);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        drawerPanel.add(dashboardicon);
        dashboardicon.setBounds(20, 210, 70, 30);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        drawerPanel.add(supporticon);
        supporticon.setBounds(20, 310, 40, 30);

        hotelprofileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotelprofile.png"))); // NOI18N
        drawerPanel.add(hotelprofileicon);
        hotelprofileicon.setBounds(20, 350, 50, 40);

        support.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("Support");
        drawerPanel.add(support);
        support.setBounds(70, 310, 160, 30);

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel.png"))); // NOI18N
        panel.setMinimumSize(new java.awt.Dimension(363, 720));
        panel.setPreferredSize(new java.awt.Dimension(330, 700));
        drawerPanel.add(panel);
        panel.setBounds(0, -10, 330, 750);

        jLabel3.setText("jLabel3");
        drawerPanel.add(jLabel3);
        jLabel3.setBounds(10, 10, 42, 17);

        jPanel1.add(drawerPanel);
        drawerPanel.setBounds(0, 0, 330, 720);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><center>\nWhere water<br> meets wonder.<br>\nLuxury redefined<br> with fluid elegance<br>\nand seamless comfort<br>\nin the city's heart.\n</center></html>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(892, 167, 180, 430);

        backimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admindash.png"))); // NOI18N
        backimage.setText("jLabel2");
        jPanel1.add(backimage);
        backimage.setBounds(0, 0, 1280, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuiconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuiconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()-> {
            new admindashboard().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JButton GenerateInvoice;
    private javax.swing.JLabel backimage;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JPanel drawerPanel;
    private javax.swing.JLabel hotelprofileicon;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuicon;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel recentbookings;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel support;
    private javax.swing.JLabel supporticon;
    // End of variables declaration//GEN-END:variables
public javax.swing.JLabel getImageLabel() {
        return image;
    }
    
    public javax.swing.JLabel getMenuIcon() {
        return menuicon;
    }
    
    public javax.swing.JPanel getDrawerPanel() {
        return drawerPanel;
    }
    
    public javax.swing.JLabel getDashboardLabel() {
        return dashboard;
    }
    
    public javax.swing.JLabel getRecentBookingsLabel() {
        return recentbookings;
    }
    
    public javax.swing.JLabel getProfileLabel() {
        return profile;
    }
    
    public javax.swing.JLabel getSupportLabel() {
        return support;
    }
    
    public javax.swing.JButton getGenerateInvoiceButton() {
        return GenerateInvoice;
    }
    
    // Listener attachment methods
    public void addGenerateInvoiceListener(java.awt.event.ActionListener listener) {
        GenerateInvoice.addActionListener(listener);
    }
    
    public void addMenuBarListener(java.awt.event.MouseListener listener) {
        menuicon.addMouseListener(listener);
    }}
