
package view;

/**
 *
 * @author Acer
 */
public class adminprofile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminprofile.class.getName());

    /**
     * Creates new form adminprofile
     */
    public adminprofile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpannel = new javax.swing.JPanel();
        HotelLogo = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        Hotelicon = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        HotelID = new javax.swing.JLabel();
        HotelIDseperator = new javax.swing.JSeparator();
        FullName = new javax.swing.JLabel();
        FullNameseperator = new javax.swing.JSeparator();
        Email = new javax.swing.JLabel();
        EmailSeperatror = new javax.swing.JSeparator();
        Phone = new javax.swing.JLabel();
        Phoneseperator = new javax.swing.JSeparator();
        Edit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Hotellogo = new javax.swing.JLabel();
        NameLogo = new javax.swing.JLabel();
        Emaillogo = new javax.swing.JLabel();
        Phonelogo = new javax.swing.JLabel();
        backgroundcolor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        backgroundpannel.setPreferredSize(new java.awt.Dimension(1280, 720));
        backgroundpannel.setLayout(null);

        HotelLogo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        HotelLogo.setForeground(new java.awt.Color(89, 4, 20));
        HotelLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\Netbeans\\Group11_Bookease_hotelbookingsystem\\src\\images\\adsT 3.png")); // NOI18N
        HotelLogo.setText("Hotel in a Tap");
        backgroundpannel.add(HotelLogo);
        HotelLogo.setBounds(110, 20, 180, 60);

        Profile.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        Profile.setForeground(new java.awt.Color(201, 12, 51));
        Profile.setText("Profile");
        backgroundpannel.add(Profile);
        Profile.setBounds(140, 290, 110, 60);

        Hotelicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\Vector (4).png")); // NOI18N
        backgroundpannel.add(Hotelicon);
        Hotelicon.setBounds(160, 200, 70, 100);

        Back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\Vector (5).png")); // NOI18N
        backgroundpannel.add(Back);
        Back.setBounds(130, 650, 50, 30);

        HotelID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        HotelID.setForeground(new java.awt.Color(255, 255, 255));
        HotelID.setText("Hotel ID");
        backgroundpannel.add(HotelID);
        HotelID.setBounds(530, 140, 60, 30);
        backgroundpannel.add(HotelIDseperator);
        HotelIDseperator.setBounds(620, 160, 250, 10);

        FullName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        FullName.setForeground(new java.awt.Color(255, 255, 255));
        FullName.setText("Full Name");
        backgroundpannel.add(FullName);
        FullName.setBounds(530, 210, 80, 30);
        backgroundpannel.add(FullNameseperator);
        FullNameseperator.setBounds(620, 233, 250, 10);

        Email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        backgroundpannel.add(Email);
        Email.setBounds(530, 280, 50, 30);
        backgroundpannel.add(EmailSeperatror);
        EmailSeperatror.setBounds(620, 300, 250, 10);

        Phone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Phone.setForeground(new java.awt.Color(255, 255, 255));
        Phone.setText("Phone");
        backgroundpannel.add(Phone);
        Phone.setBounds(530, 350, 50, 30);
        backgroundpannel.add(Phoneseperator);
        Phoneseperator.setBounds(620, 370, 250, 20);

        Edit.setBackground(new java.awt.Color(184, 12, 47));
        Edit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Edit.setForeground(new java.awt.Color(232, 128, 153));
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        backgroundpannel.add(Edit);
        Edit.setBounds(510, 470, 80, 28);

        Cancel.setBackground(new java.awt.Color(184, 12, 47));
        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Cancel.setForeground(new java.awt.Color(232, 128, 153));
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        backgroundpannel.add(Cancel);
        Cancel.setBounds(790, 470, 80, 28);

        Logout.setBackground(new java.awt.Color(184, 12, 47));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Logout.setForeground(new java.awt.Color(232, 128, 153));
        Logout.setText("Logout");
        backgroundpannel.add(Logout);
        Logout.setBounds(650, 540, 90, 28);

        Hotellogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\id-badge.png")); // NOI18N
        backgroundpannel.add(Hotellogo);
        Hotellogo.setBounds(850, 124, 20, 40);

        NameLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\image 8.png")); // NOI18N
        backgroundpannel.add(NameLogo);
        NameLogo.setBounds(850, 200, 20, 40);

        Emaillogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\image 8 (1).png")); // NOI18N
        backgroundpannel.add(Emaillogo);
        Emaillogo.setBounds(850, 280, 30, 20);

        Phonelogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\image 8 (2).png")); // NOI18N
        backgroundpannel.add(Phonelogo);
        Phonelogo.setBounds(850, 350, 37, 16);

        backgroundcolor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-24 082945.png"))); // NOI18N
        backgroundpannel.add(backgroundcolor);
        backgroundcolor.setBounds(-20, 10, 1740, 720);

        getContentPane().add(backgroundpannel);
        backgroundpannel.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminprofile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel Email;
    private javax.swing.JSeparator EmailSeperatror;
    private javax.swing.JLabel Emaillogo;
    private javax.swing.JLabel FullName;
    private javax.swing.JSeparator FullNameseperator;
    private javax.swing.JLabel HotelID;
    private javax.swing.JSeparator HotelIDseperator;
    private javax.swing.JLabel HotelLogo;
    private javax.swing.JLabel Hotelicon;
    private javax.swing.JLabel Hotellogo;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NameLogo;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Phonelogo;
    private javax.swing.JSeparator Phoneseperator;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel backgroundcolor;
    private javax.swing.JPanel backgroundpannel;
    // End of variables declaration//GEN-END:variables
}
