/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());
    private static final long serialVersionUID = 1L;

    
   
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpannel = new javax.swing.JPanel();
        hamburgermenu = new javax.swing.JLabel();
        RecentBooking = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        Support = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        Admindashboard = new javax.swing.JLabel();
        Rooms = new javax.swing.JLabel();
        AvailableRooms = new javax.swing.JLabel();
        TodaysBooking = new javax.swing.JLabel();
        hamburgermenubutton = new javax.swing.JButton();
        backgrounddashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        backgroundpannel.setPreferredSize(new java.awt.Dimension(1280, 720));
        backgroundpannel.setLayout(null);
        backgroundpannel.add(hamburgermenu);
        hamburgermenu.setBounds(170, 20, 30, 40);

        RecentBooking.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RecentBooking.setForeground(new java.awt.Color(255, 255, 255));
        RecentBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecentBooking.setText("   Recent Booking");
        RecentBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecentBookingMouseClicked(evt);
            }
        });
        backgroundpannel.add(RecentBooking);
        RecentBooking.setBounds(170, 300, 270, 40);

        Profile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Profile.setForeground(new java.awt.Color(255, 255, 255));
        Profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile.setText("    Profile");
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        backgroundpannel.add(Profile);
        Profile.setBounds(170, 440, 190, 40);

        Support.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Support.setForeground(new java.awt.Color(255, 255, 255));
        Support.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Support.setText("   Support");
        Support.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupportMouseClicked(evt);
            }
        });
        backgroundpannel.add(Support);
        Support.setBounds(170, 370, 190, 40);

        Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.setText("   Dashboard");
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        backgroundpannel.add(Dashboard);
        Dashboard.setBounds(150, 240, 270, 40);

        Admindashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Admindashboard.setForeground(new java.awt.Color(232, 128, 153));
        Admindashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Admindashboard.setText("Admin Dashboard");
        backgroundpannel.add(Admindashboard);
        Admindashboard.setBounds(710, 60, 360, 50);

        Rooms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rooms.setForeground(new java.awt.Color(255, 255, 255));
        Rooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rooms.setText("Total Rooms: 100");
        backgroundpannel.add(Rooms);
        Rooms.setBounds(740, 250, 270, 60);

        AvailableRooms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AvailableRooms.setForeground(new java.awt.Color(255, 255, 255));
        AvailableRooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvailableRooms.setText("Available Rooms : 1");
        backgroundpannel.add(AvailableRooms);
        AvailableRooms.setBounds(740, 320, 270, 60);

        TodaysBooking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TodaysBooking.setForeground(new java.awt.Color(255, 255, 255));
        TodaysBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TodaysBooking.setText("Total Bookings Today : 1");
        backgroundpannel.add(TodaysBooking);
        TodaysBooking.setBounds(740, 390, 270, 60);

        hamburgermenubutton.setBackground(new java.awt.Color(217, 217, 217));
        hamburgermenubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburgermenubuttonActionPerformed(evt);
            }
        });
        backgroundpannel.add(hamburgermenubutton);
        hamburgermenubutton.setBounds(160, 20, 50, 40);
        backgroundpannel.add(backgrounddashboard);
        backgrounddashboard.setBounds(49, 0, 0, 0);

        getContentPane().add(backgroundpannel);
        backgroundpannel.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hamburgermenubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburgermenubuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hamburgermenubuttonActionPerformed

    private void RecentBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecentBookingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RecentBookingMouseClicked

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileMouseClicked

    private void SupportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SupportMouseClicked

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admindashboard;
    private javax.swing.JLabel AvailableRooms;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel RecentBooking;
    private javax.swing.JLabel Rooms;
    private javax.swing.JLabel Support;
    private javax.swing.JLabel TodaysBooking;
    private javax.swing.JLabel backgrounddashboard;
    private javax.swing.JPanel backgroundpannel;
    private javax.swing.JLabel hamburgermenu;
    private javax.swing.JButton hamburgermenubutton;
    // End of variables declaration//GEN-END:variables

    public Object getProfileLabel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getSupportLabel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getRecentBookingLabel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getDashboardLabel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}



