/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BooknowController;
import javax.swing.*;

/**
 *
 * @author sailenawale
 */
public class book extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(book.class.getName());
    private BooknowController controller;
    /**
     * Creates new form book
     */
    public book() {
        initComponents();         
        
       
    }
    
    // Add a getter for the connection (optional, useful for testing)
    public void setController(BooknowController controller) {
        this.controller = controller;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkoutdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numberofpeople = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        roomtype = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        checkindate = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Room Type:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 170, 130, 40);

        checkoutdate.setPreferredSize(new java.awt.Dimension(175, 34));
        jPanel1.add(checkoutdate);
        checkoutdate.setBounds(170, 470, 280, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" No. of People");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 260, 150, 40);
        jPanel1.add(numberofpeople);
        numberofpeople.setBounds(170, 300, 280, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check-In-Date:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 360, 150, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check-Out-Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 440, 160, 21);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Delux", "Suite", " " }));
        
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(350, 220, 90, 23);

        roomtype.setEditable(false);
        jPanel1.add(roomtype);
        roomtype.setBounds(170, 210, 280, 40);

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 400, 42, 17);
        jPanel1.add(checkindate);
        checkindate.setBounds(170, 390, 280, 40);

        confirm.setBackground(new java.awt.Color(184, 13, 47));
        confirm.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        confirm.setForeground(new java.awt.Color(241, 151, 174));
        confirm.setText("Confirm");
        jPanel1.add(confirm);
        confirm.setBounds(238, 535, 130, 40);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        logo.setText("jLabel10");
        jPanel1.add(logo);
        logo.setBounds(0, -20, 90, 100);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(100, 40, 90, 16);

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backbutton.png"))); // NOI18N
        
        jPanel1.add(backbutton);
        backbutton.setBounds(30, 640, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookpage.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new book().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JTextField checkindate;
    private javax.swing.JTextField checkoutdate;
    private javax.swing.JButton confirm;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField numberofpeople;
    private javax.swing.JTextField roomtype;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables

public JButton getConfirmButton() {
        return confirm;
    }
public JLabel getBackButton() {  // ADD THIS GETTER
        return backbutton;
    }
    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JTextField getRoomtype() {
        return roomtype;
    }

    public JTextField getNumberofpeople() {
        return numberofpeople;
    }

    public JTextField getCheckindate() {
        return checkindate;
    }

    public JTextField getCheckoutdate() {
        return checkoutdate;
    }

    // Make this method public so the controller can call it
    public void clearForm() {
        jComboBox1.setSelectedIndex(0);
        roomtype.setText("");
        numberofpeople.setText("");
        checkindate.setText("");
        checkoutdate.setText("");
        // roomtype.setEnabled(false); // uncomment if you want to keep this
    }
public String getComboBoxSelectedItem() {
    return (String) jComboBox1.getSelectedItem();
}

// Setter for text field
public void setRoomTypeText(String text) {
    roomtype.setText(text);
}

// Getter for combo box component (for adding listeners)
public JComboBox<String> getComboBox() {
    return jComboBox1;
}

   
}
