/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author sailenawale
 */
public class bookinghistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bookinghistory.class.getName());
  
    
    private int userId = 1; // Your user ID
    
    public bookinghistory() {
        initComponents();
        setupTable();
        loadBookings();
        setLocationRelativeTo(null); // Center window
    }
    
    private void setupTable() {
        String[] columns = {"ID", "Hotel", "Check-in", "Check-out", "Price", "Status"};
        DefaultTableModel model = new DefaultTableModel(columns, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table read-only
            }
        };
        table.setModel(model); // CHANGE jTable1 to YOUR table's variable name
    }
  
    
  
      private void loadBookings() {
        try {
            // 1. Connect to database
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/hotel_booking", 
                "root", 
                "shr7y42007@#"
            );
            
            // 2. Get bookings for this user
            String sql = "SELECT * FROM bookings WHERE user_id = ? ORDER BY booking_id DESC";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, userId);
            
            // 3. Execute query
            ResultSet rs = stmt.executeQuery();
            
            // 4. Get table model and clear old data
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            
            // 5. Add each booking to table
            boolean hasData = false;
            while (rs.next()) {
                hasData = true;
                Object[] row = {
                    rs.getInt("booking_id"),
                    rs.getString("hotel_name"),
                    rs.getString("check_in_date"),
                    rs.getString("check_out_date"),
                    "Rs " + rs.getDouble("price"), // Changed $ to Rs
                    rs.getString("status")
                };
                model.addRow(row);
            }
            
            // 6. Close connections
            rs.close();
            stmt.close();
            conn.close();
            
            // 7. If no bookings, show message
            if (!hasData) {
                JOptionPane.showMessageDialog(this,
                    "No bookings found.\nBook hotels from dashboard first!",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * Creates new form bookinghistory
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bookinghistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        scroll = new javax.swing.JScrollBar();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        bookinghistory.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bookinghistory.setForeground(new java.awt.Color(232, 128, 153));
        bookinghistory.setText("Booking History");
        jPanel1.add(bookinghistory);
        bookinghistory.setBounds(420, 20, 330, 44);

        table.setBackground(new java.awt.Color(255, 180, 170));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "user_id", "booking_id", "hotel_name", "check_in_date", "check_out_date", "status", "price"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 160, 920, 440);
        jPanel1.add(scroll);
        scroll.setBounds(1040, 160, 20, 440);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookinghistory.png"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(0, -10, 1200, 690);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-3, 0, 1280, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bookinghistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookinghistory;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollBar scroll;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
