package view;

import controller.BooknowController;
import javax.swing.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import database.MySqlConnection; // Add this import
import java.awt.HeadlessException;
import java.sql.SQLException;

public class booknow extends JFrame {
    private Connection connection;
    private BooknowController controller; // Add controller reference

      private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(booknow.class.getName());
      
    // Constructor must be BEFORE initComponents
    public booknow() {
        initComponents();
        initializeDatabaseConnection();
        
        // Initialize the controller AFTER the connection is established
        if (connection != null) {
            controller = new BooknowController(this, connection);
        } else {
            JOptionPane.showMessageDialog(this,
                "Cannot initialize booking controller due to database connection failure",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Add a getter for the connection (optional, useful for testing)
    public Connection getConnection() {
        return connection;
     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
 
    
    
    @SuppressWarnings("unchecked")
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new booknow().setVisible(true));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

       



        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkoutdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numberofpeople = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        roomtype = new javax.swing.JTextField();
        checkindate = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Room Type:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 170, 120, 40);

        checkoutdate.setPreferredSize(new java.awt.Dimension(175, 34));
        jPanel1.add(checkoutdate);
        checkoutdate.setBounds(190, 470, 260, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" No. of People");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 260, 150, 40);
        jPanel1.add(numberofpeople);
        numberofpeople.setBounds(190, 300, 260, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check-In-Date:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 360, 150, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check-Out-Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 440, 160, 21);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Delux", "Suite", " " }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(190, 210, 260, 40);
        jPanel1.add(roomtype);
        roomtype.setBounds(190, 210, 260, 40);
        jPanel1.add(checkindate);
        checkindate.setBounds(190, 390, 260, 40);

        confirm.setBackground(new java.awt.Color(184, 13, 47));
        confirm.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        confirm.setForeground(new java.awt.Color(241, 151, 174));
        confirm.setText("Confirm");
        jPanel1.add(confirm);
        confirm.setBounds(250, 540, 116, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/booking_page_image.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1280, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("bookingpage");

        pack();
    }// </editor-fold>                        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField checkindate;
    private javax.swing.JTextField checkoutdate;
    private javax.swing.JButton confirm;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numberofpeople;
    private javax.swing.JTextField roomtype;
    // End of variables declaration//GEN-END:variables

        // ================== PUBLIC GETTERS FOR CONTROLLER (ADD HERE) ==================

    public JButton getConfirmButton() {
        return confirm;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JTextField getRoomtype() {
        return roomtype;
    }

    public JTextField getNumberofpeople() {
        return numberofpeople;
    }

    public JTextField getCheckindate() {
        return checkindate;
    }

    public JTextField getCheckoutdate() {
        return checkoutdate;
    }

    // Make this method public so the controller can call it
    public void clearForm() {
        jComboBox1.setSelectedIndex(0);
        roomtype.setText("");
        numberofpeople.setText("");
        checkindate.setText("");
        checkoutdate.setText("");
        // roomtype.setEnabled(false); // uncomment if you want to keep this
    }

private void initializeDatabaseConnection() {
    try {
        // Create an instance of your MySqlConnection class
        MySqlConnection mysqlConn = new MySqlConnection();
        
        // Use the openConnection() method from your class
        connection = mysqlConn.openConnection();
        
        // Optional: Check if connection is successful
        if (connection != null && !connection.isClosed()) {
            System.out.println("Database connection established successfully!");
        } else {
            JOptionPane.showMessageDialog(this, 
                "Failed to establish database connection",
                "Connection Error", 
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Database connection error: " + e.getMessage(),
            "Connection Error", 
            JOptionPane.ERROR_MESSAGE);
    }
  }
}
   

  
      
            
