/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.User;
import model.Booking;
import dao.BookingDAO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author sailenawale
 */
private User currentUser;
    private javax.swing.JTable bookingTable;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form bookinghistory
     */
    public bookinghistory(User currentUser) {
        this.currentUser = currentUser;
        initComponents();
        addBookingHistoryTable();
        loadBookingData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 42, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // ADD THIS METHOD: Add booking table to existing panel
    private void addBookingHistoryTable() {
        // Remove the jLabel1
        jPanel1.remove(jLabel1);
        
        // Create table model
        String[] columns = {"Booking ID", "Hotel", "Check-in", "Check-out", "Status", "Price"};
        tableModel = new DefaultTableModel(columns, 0);
        
        // Create table
        bookingTable = new javax.swing.JTable(tableModel);
        bookingTable.setBounds(50, 50, 1100, 500);
        bookingTable.setRowHeight(40);
        bookingTable.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        
        // Add to panel
        jPanel1.add(bookingTable);
        
        // Add title
        JLabel title = new JLabel("MY BOOKING HISTORY");
        title.setBounds(50, 10, 400, 30);
        title.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        title.setForeground(java.awt.Color.WHITE);
        jPanel1.add(title);
    }
    
    // ADD THIS METHOD: Load data from database
    private void loadBookingData() {
        try {
            // Get bookings from DAO
            BookingDAO bookingDAO = new BookingDAO();
            List<Booking> bookings = bookingDAO.getUserBookings(currentUser.getId());
            
            // Clear table
            tableModel.setRowCount(0);
            
            // Add data to table
            for (Booking booking : bookings) {
                Object[] row = {
                    booking.getBooking_ID(),
                    booking.getHotelName(),
                    booking.getCheck_in_date(),
                    booking.getCheck_out_date(),
                    booking.getStatus(),
                    String.format("$%.2f", booking.getPrice())
                };
                tableModel.addRow(row);
            }
            
            // If no bookings, show message
            if (bookings.isEmpty()) {
                tableModel.addRow(new Object[]{"No bookings found", "", "", "", "", ""});
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            tableModel.addRow(new Object[]{"Error loading data", e.getMessage(), "", "", "", ""});
        }
    }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bookinghistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables



