/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BookingConfirmationController;

/**
 *
 * @author sailenawale
 */
public class confirmation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(confirmation.class.getName());

    /**
     * Creates new form confirmation
     */
    public confirmation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        paynowbutton = new javax.swing.JButton();
        bookingconfirmation = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        bookingid = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        statusfield = new javax.swing.JTextField();
        bookingidfieldid = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(120, 40, 90, 16);

        paynowbutton.setBackground(new java.awt.Color(184, 13, 47));
        paynowbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        paynowbutton.setForeground(new java.awt.Color(241, 151, 174));
        paynowbutton.setText("Pay now");
        paynowbutton.setBorder(null);
        jPanel1.add(paynowbutton);
        paynowbutton.setBounds(590, 440, 160, 40);

        bookingconfirmation.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        bookingconfirmation.setForeground(new java.awt.Color(232, 128, 153));
        bookingconfirmation.setText("Booking Confirmation");
        jPanel1.add(bookingconfirmation);
        bookingconfirmation.setBounds(460, 120, 410, 60);
        jPanel1.add(text);
        text.setBounds(380, 230, 520, 40);

        bookingid.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        bookingid.setForeground(new java.awt.Color(255, 255, 255));
        bookingid.setText("Booking ID: ");
        jPanel1.add(bookingid);
        bookingid.setBounds(380, 270, 110, 30);

        status.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Status: ");
        jPanel1.add(status);
        status.setBounds(380, 350, 80, 40);

        date.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date:");
        jPanel1.add(date);
        date.setBounds(380, 310, 50, 30);

        datefield.setEditable(false);
        jPanel1.add(datefield);
        datefield.setBounds(510, 310, 400, 40);

        statusfield.setEditable(false);
        jPanel1.add(statusfield);
        statusfield.setBounds(510, 360, 400, 40);

        bookingidfieldid.setEditable(false);
        jPanel1.add(bookingidfieldid);
        bookingidfieldid.setBounds(510, 253, 400, 40);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(0, 0, 1280, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {BookingConfirmationController.show(1);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingconfirmation;
    private javax.swing.JLabel bookingid;
    private javax.swing.JTextField bookingidfieldid;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datefield;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton paynowbutton;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel status;
    private javax.swing.JTextField statusfield;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
// Getter methods for controller
public javax.swing.JTextField getBookingIdField() {
    return bookingidfieldid;
}

public javax.swing.JTextField getDateField() {
    return datefield;
}

public javax.swing.JTextField getStatusField() {
    return statusfield;
}


public javax.swing.JLabel getTextLabel() {
    return text;
}

public javax.swing.JButton getPayNowButton() {
    return paynowbutton;
}}
