/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.sun.jdi.connect.spi.Connection;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author sailenawale
 */
public class dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userdashboard = new javax.swing.JLabel();
        hotelid1 = new javax.swing.JLabel();
        hotelname1 = new javax.swing.JLabel();
        Location2 = new javax.swing.JLabel();
        roomstatus2 = new javax.swing.JLabel();
        Ratings2 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        hotelid = new javax.swing.JLabel();
        hotelname = new javax.swing.JLabel();
        Location1 = new javax.swing.JLabel();
        roomstatus1 = new javax.swing.JLabel();
        Ratings1 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        bookinghistory = new javax.swing.JLabel();
        notificationlabel = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        notificationsicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        profileicon = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        viewdetails3 = new javax.swing.JButton();
        viewdetails4 = new javax.swing.JButton();
        support1 = new javax.swing.JLabel();
        support2 = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        dashboardimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newmo_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(310, 180));
        jLabel1.setMinimumSize(new java.awt.Dimension(310, 180));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(750, 160, 250, 170);

        userdashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        userdashboard.setForeground(new java.awt.Color(232, 128, 153));
        userdashboard.setText("User Dashboard");
        jPanel1.add(userdashboard);
        userdashboard.setBounds(490, 60, 290, 30);

        hotelid1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        hotelid1.setText("Hotel ID: 101  ");
        jPanel1.add(hotelid1);
        hotelid1.setBounds(420, 340, 170, 30);

        hotelname1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotelname1.setText("Hotel Name: Aquaphor  ");
        jPanel1.add(hotelname1);
        hotelname1.setBounds(420, 370, 260, 30);

        Location2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Location2.setText("Location: Lalitpur");
        jPanel1.add(Location2);
        Location2.setBounds(420, 400, 260, 30);

        roomstatus2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        roomstatus2.setText("Room status: Available  ");
        jPanel1.add(roomstatus2);
        roomstatus2.setBounds(420, 430, 244, 30);

        Ratings2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ratings2.setText("Rating:       4.5");
        jPanel1.add(Ratings2);
        Ratings2.setBounds(420, 460, 170, 30);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/⭐_1.png"))); // NOI18N
        jPanel1.add(star2);
        star2.setBounds(820, 460, 30, 30);

        hotelid.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        hotelid.setText("Hotel ID: 102  ");
        jPanel1.add(hotelid);
        hotelid.setBounds(760, 340, 170, 30);

        hotelname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotelname.setText("Hotel Name: Skyscraper  ");
        jPanel1.add(hotelname);
        hotelname.setBounds(760, 370, 260, 30);

        Location1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Location1.setText("Location: Lalitpur");
        jPanel1.add(Location1);
        Location1.setBounds(760, 400, 310, 30);

        roomstatus1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        roomstatus1.setText("Room status: Unavailable  ");
        jPanel1.add(roomstatus1);
        roomstatus1.setBounds(760, 430, 271, 30);

        Ratings1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ratings1.setText("Rating:       5");
        jPanel1.add(Ratings1);
        Ratings1.setBounds(760, 460, 170, 30);

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/⭐_1.png"))); // NOI18N
        jPanel1.add(star3);
        star3.setBounds(480, 460, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 150, 255, 180);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(940, 60, 40, 30);

        bookinghistory.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bookinghistory.setForeground(new java.awt.Color(255, 255, 255));
        bookinghistory.setText("Booking History");
        bookinghistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookinghistoryMouseClicked(evt);
            }
        });
        jPanel1.add(bookinghistory);
        bookinghistory.setBounds(70, 190, 220, 30);

        notificationlabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        notificationlabel.setForeground(new java.awt.Color(255, 255, 255));
        notificationlabel.setText("Notifications");
        notificationlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationlabelMouseClicked(evt);
            }
        });
        jPanel1.add(notificationlabel);
        notificationlabel.setBounds(70, 240, 150, 20);

        profile.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jPanel1.add(profile);
        profile.setBounds(70, 320, 150, 32);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        jPanel1.add(dashboardicon);
        dashboardicon.setBounds(20, 150, 42, 30);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        jPanel1.add(bookingicon);
        bookingicon.setBounds(20, 185, 50, 40);

        notificationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notifications.png"))); // NOI18N
        jPanel1.add(notificationsicon);
        notificationsicon.setBounds(20, 230, 50, 40);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        jPanel1.add(supporticon);
        supporticon.setBounds(20, 280, 60, 25);

        profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vector.png"))); // NOI18N
        jPanel1.add(profileicon);
        profileicon.setBounds(20, 320, 40, 27);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hamburger Menu.png"))); // NOI18N
        jPanel1.add(menu);
        menu.setBounds(10, 10, 40, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 600, 130, 90);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(90, 660, 90, 16);

        viewdetails3.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        viewdetails3.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails3.setText("View details");
        viewdetails3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails3ActionPerformed(evt);
            }
        });
        jPanel1.add(viewdetails3);
        viewdetails3.setBounds(750, 510, 250, 50);

        viewdetails4.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        viewdetails4.setForeground(new java.awt.Color(255, 255, 255));
        viewdetails4.setText("View details");
        viewdetails4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails4ActionPerformed(evt);
            }
        });
        jPanel1.add(viewdetails4);
        viewdetails4.setBounds(420, 510, 240, 50);

        support1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        support1.setForeground(new java.awt.Color(255, 255, 255));
        support1.setText("Dashboard");
        support1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                support1MouseClicked(evt);
            }
        });
        jPanel1.add(support1);
        support1.setBounds(70, 150, 150, 30);

        support2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        support2.setForeground(new java.awt.Color(255, 255, 255));
        support2.setText("Support");
        support2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                support2MouseClicked(evt);
            }
        });
        jPanel1.add(support2);
        support2.setBounds(70, 280, 150, 30);

        searchbar.setText("search here");
        searchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchbarFocusLost(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        jPanel1.add(searchbar);
        searchbar.setBounds(780, 60, 140, 30);

        dashboardimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/w_2.png"))); // NOI18N
        dashboardimage.setText("s");
        jPanel1.add(dashboardimage);
        dashboardimage.setBounds(-20, -60, 1280, 850);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetails3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails3ActionPerformed

    private void viewdetails4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetails4ActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
                                                                         

    }//GEN-LAST:event_searchMouseClicked

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:                                                   
    String searchText = searchbar.getText().trim();
    
    try {
        // Load driver and connect
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection conn = java.sql.DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/hotel_booking", "root", "shr7y42007@#");
        
        // Search by name column (NOT hotel_name)
        String sql = "SELECT * FROM hotels WHERE name LIKE ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, "%" + searchText + "%");
        
        java.sql.ResultSet rs = pstmt.executeQuery();
        
        // Show results
        String result = "";
        while (rs.next()) {
            result += rs.getString("name") + " (ID: " + rs.getInt("hotel_id") + ")\n";
        }
        
        if (result.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hotels found");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Found:\n" + result);
        }
        
        conn.close();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_searchbarActionPerformed

    private void searchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusGained
        // TODO add your handling code here:
        if(searchbar.getText().equals("search here")){
            searchbar.setText("");
        }
    }//GEN-LAST:event_searchbarFocusGained

    private void searchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusLost
        // TODO add your handling code here:
        if(searchbar.getText().equals("")){
           searchbar.setText("search here");}
    }//GEN-LAST:event_searchbarFocusLost

    private void notificationlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationlabelMouseClicked
        // TODO add your handling code here:
    this.dispose();
    
    // Open notifications
    new notifications().setVisible(true);

    }//GEN-LAST:event_notificationlabelMouseClicked

    private void support2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_support2MouseClicked
        // TODO add your handling code here:
         this.dispose();
    
    // Open sipport
    new support().setVisible(true);

    }//GEN-LAST:event_support2MouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
         this.dispose();
    
    // Open profile
    new profile().setVisible(true);

    }//GEN-LAST:event_profileMouseClicked

    private void support1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_support1MouseClicked
        // TODO add your handling code here:
         this.dispose();
    
    // Open dashboard
    new dashboard().setVisible(true);

    }//GEN-LAST:event_support1MouseClicked

    private void bookinghistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookinghistoryMouseClicked
        // TODO add your handling code here:
         this.dispose();
    
    // Open bookinghistory
    new bookinghistory().setVisible(true);

    }//GEN-LAST:event_bookinghistoryMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Location1;
    private javax.swing.JLabel Location2;
    private javax.swing.JLabel Ratings1;
    private javax.swing.JLabel Ratings2;
    private javax.swing.JLabel bookinghistory;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JLabel dashboardimage;
    private javax.swing.JLabel hotelid;
    private javax.swing.JLabel hotelid1;
    private javax.swing.JLabel hotelname;
    private javax.swing.JLabel hotelname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel notificationlabel;
    private javax.swing.JLabel notificationsicon;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileicon;
    private javax.swing.JLabel roomstatus1;
    private javax.swing.JLabel roomstatus2;
    private javax.swing.JLabel search;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel support1;
    private javax.swing.JLabel support2;
    private javax.swing.JLabel supporticon;
    private javax.swing.JLabel userdashboard;
    private javax.swing.JButton viewdetails3;
    private javax.swing.JButton viewdetails4;
    // End of variables declaration//GEN-END:variables
}
