/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
/**
 *
 * @author sailenawale
 */
public class hotelcard extends javax.swing.JPanel {

    public static void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form hotelcard
     */
    public hotelcard() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewdetails = new javax.swing.JButton();
        hotelid = new javax.swing.JLabel();
        hotelname = new javax.swing.JLabel();
        Location1 = new javax.swing.JLabel();
        roomstatus1 = new javax.swing.JLabel();
        Ratings1 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();

        jLabel1.setBounds(new java.awt.Rectangle(10, 10, 280, 180));

        viewdetails.setBackground(new java.awt.Color(246, 80, 90));
        viewdetails.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        viewdetails.setForeground(new java.awt.Color(255, 0, 51));
        viewdetails.setText("View details");
        viewdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailsActionPerformed(evt);
            }
        });

        hotelid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotelid.setText("Hotel_id:   ");

        hotelname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotelname.setText("Hotel_name:  ");

        Location1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Location1.setText("Location: ");

        roomstatus1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        roomstatus1.setText("Room_status: ");

        Ratings1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ratings1.setText("Rating:");

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/⭐_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomstatus1)
                    .addComponent(Location1)
                    .addComponent(hotelid)
                    .addComponent(hotelname))
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ratings1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hotelid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotelname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Location1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(star3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ratings1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(viewdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailsActionPerformed
        // TODO add your handling code here 
    }//GEN-LAST:event_viewdetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Location1;
    private javax.swing.JLabel Ratings1;
    private javax.swing.JLabel hotelid;
    private javax.swing.JLabel hotelname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel roomstatus1;
    private javax.swing.JLabel star3;
    private javax.swing.JButton viewdetails;
    // End of variables declaration//GEN-END:variables
    public void addViewDetailsListener(java.awt.event.ActionListener listener) {
        viewdetails.addActionListener(listener);
    }
    
    public javax.swing.JButton getViewDetailsButton() {
        return viewdetails;
    }
    
    public javax.swing.JLabel getHotelIdLabel() {
        return hotelid;
    }
    
    public javax.swing.JLabel getHotelNameLabel() {
        return hotelname;
    }
    
    public javax.swing.JLabel getLocationLabel() {
        return Location1;
    }
    
    public javax.swing.JLabel getRoomStatusLabel() {
        return roomstatus1;
    }
    
    public javax.swing.JLabel getRatingLabel() {
        return Ratings1;
    }
    
    public javax.swing.JLabel getImageLabel() {
        return jLabel1;
    }
    public void setImage(javax.swing.ImageIcon image) {
    jLabel1.setIcon(image);
  }
}
