/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.InvoiceController;

/**
 *
 * @author sailenawale
 */
public class invoice extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(invoice.class.getName());
    private int userId;
    /**
     * Creates new form in
     */
    public invoice(int userId) {
        this.userId = userId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalcharge = new javax.swing.JLabel();
        notifications = new javax.swing.JLabel();
        invoiceid = new javax.swing.JLabel();
        hotelid = new javax.swing.JLabel();
        checkoutdate = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        checkindate = new javax.swing.JLabel();
        paymentmethod = new javax.swing.JLabel();
        paymentstatus = new javax.swing.JLabel();
        roomcharge = new javax.swing.JLabel();
        extracharge = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        bookingid = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        totalcharge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        totalcharge.setForeground(new java.awt.Color(255, 255, 255));
        totalcharge.setText("Total charge: ");
        jPanel1.add(totalcharge);
        totalcharge.setBounds(360, 590, 550, 40);

        notifications.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        notifications.setForeground(new java.awt.Color(232, 128, 153));
        notifications.setText("Invoice");
        jPanel1.add(notifications);
        notifications.setBounds(510, 40, 150, 40);

        invoiceid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        invoiceid.setForeground(new java.awt.Color(255, 255, 255));
        invoiceid.setText("Invoice ID:");
        jPanel1.add(invoiceid);
        invoiceid.setBounds(360, 160, 550, 30);

        hotelid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotelid.setForeground(new java.awt.Color(255, 255, 255));
        hotelid.setText("Hotel ID:");
        jPanel1.add(hotelid);
        hotelid.setBounds(360, 280, 550, 30);

        checkoutdate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        checkoutdate.setForeground(new java.awt.Color(255, 255, 255));
        checkoutdate.setText("Check-out-date:");
        jPanel1.add(checkoutdate);
        checkoutdate.setBounds(360, 400, 550, 30);

        fullname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setText("Full name:");
        jPanel1.add(fullname);
        fullname.setBounds(360, 320, 560, 30);

        checkindate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        checkindate.setForeground(new java.awt.Color(255, 255, 255));
        checkindate.setText("Check-in-date: ");
        jPanel1.add(checkindate);
        checkindate.setBounds(360, 360, 550, 30);

        paymentmethod.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        paymentmethod.setForeground(new java.awt.Color(255, 255, 255));
        paymentmethod.setText("Payment method:");
        jPanel1.add(paymentmethod);
        paymentmethod.setBounds(360, 440, 550, 30);

        paymentstatus.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        paymentstatus.setForeground(new java.awt.Color(255, 255, 255));
        paymentstatus.setText("Payment status:");
        jPanel1.add(paymentstatus);
        paymentstatus.setBounds(360, 480, 550, 30);

        roomcharge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        roomcharge.setForeground(new java.awt.Color(255, 255, 255));
        roomcharge.setText("Room charge:");
        jPanel1.add(roomcharge);
        roomcharge.setBounds(360, 520, 550, 30);

        extracharge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        extracharge.setForeground(new java.awt.Color(255, 255, 255));
        extracharge.setText("Extra charge:");
        jPanel1.add(extracharge);
        extracharge.setBounds(360, 560, 550, 30);

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backbutton.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(40, 640, 40, 30);

        bookingid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bookingid.setForeground(new java.awt.Color(255, 255, 255));
        bookingid.setText("Booking ID:");
        jPanel1.add(bookingid);
        bookingid.setBounds(360, 200, 550, 30);

        userid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setText("User ID:");
        jPanel1.add(userid);
        userid.setBounds(360, 240, 550, 30);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(140, 50, 90, 16);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 1280, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        int userId = 1;
        invoice invoiceFrame = new invoice(userId);
        
        
        InvoiceController controller = new InvoiceController(invoiceFrame);
        controller.showInvoice(userId);  
        controller.setupBackButton();
        
        invoiceFrame.setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JLabel bookingid;
    private javax.swing.JLabel checkindate;
    private javax.swing.JLabel checkoutdate;
    private javax.swing.JLabel extracharge;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel hotelid;
    private javax.swing.JLabel image;
    private javax.swing.JLabel invoiceid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel notifications;
    private javax.swing.JLabel paymentmethod;
    private javax.swing.JLabel paymentstatus;
    private javax.swing.JLabel roomcharge;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel totalcharge;
    private javax.swing.JLabel userid;
    // End of variables declaration//GEN-END:variables

public javax.swing.JLabel getInvoiceIdLabel() {
    return invoiceid;
}
public javax.swing.JLabel getBookingIdLabel() {
    return bookingid;
}
public javax.swing.JLabel getUserIdLabel() {
    return userid;
}
public javax.swing.JLabel getHotelIdLabel() {
    return hotelid;
}
public javax.swing.JLabel getFullNameLabel() {
    return fullname;
}
public javax.swing.JLabel getCheckInDateLabel() { 
    return checkindate;
}
public javax.swing.JLabel getCheckOutDateLabel() {
    return checkoutdate; 
}
public javax.swing.JLabel getPaymentMethodLabel() {
    return paymentmethod; 
}
public javax.swing.JLabel getPaymentStatusLabel() {
    return paymentstatus;
}
public javax.swing.JLabel getRoomChargeLabel() {
    return roomcharge; 
}
public javax.swing.JLabel getExtraChargeLabel() {
    return extracharge;
}
public javax.swing.JLabel getTotalChargeLabel() {
    return totalcharge;
}
public javax.swing.JLabel getBackButtonLabel() {
    return backbutton; 
}
}
