/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author hp
 */
public class LOGIN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LOGIN.class.getName());

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Login1 = new javax.swing.JLabel();
        ACC = new javax.swing.JLabel();
        Forgetpwd = new javax.swing.JLabel();
        Mailbox = new javax.swing.JLabel();
        key = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Hoteltap = new javax.swing.JLabel();
        redbox = new javax.swing.JButton();
        layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 0, 153));
        Login.setText("Login ");
        getContentPane().add(Login);
        Login.setBounds(800, 110, 130, 60);

        Password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(Password);
        Password.setBounds(710, 320, 310, 34);

        Email.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(Email);
        Email.setBounds(710, 220, 300, 30);

        Login1.setBackground(new java.awt.Color(200, 0, 40));
        Login1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login1.setForeground(new java.awt.Color(255, 0, 153));
        Login1.setText("       Login");
        getContentPane().add(Login1);
        Login1.setBounds(800, 450, 140, 30);

        ACC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ACC.setForeground(new java.awt.Color(255, 255, 255));
        ACC.setText("Create an account");
        getContentPane().add(ACC);
        ACC.setBounds(700, 510, 150, 30);

        Forgetpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Forgetpwd.setForeground(new java.awt.Color(255, 255, 255));
        Forgetpwd.setText("Forget password ?");
        getContentPane().add(Forgetpwd);
        Forgetpwd.setBounds(910, 510, 170, 30);

        Mailbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mailbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 3.png"))); // NOI18N
        getContentPane().add(Mailbox);
        Mailbox.setBounds(990, 180, 50, 110);

        key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 1.png"))); // NOI18N
        getContentPane().add(key);
        key.setBounds(990, 300, 30, 60);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(70, 40, 100, 90);

        Hoteltap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hotel in a Tap.png"))); // NOI18N
        getContentPane().add(Hoteltap);
        Hoteltap.setBounds(140, 40, 110, 40);

        redbox.setBackground(new java.awt.Color(204, 0, 0));
        redbox.setForeground(new java.awt.Color(255, 0, 102));
        redbox.setBorder(null);
        redbox.addActionListener(this::redboxActionPerformed);
        getContentPane().add(redbox);
        redbox.setBounds(770, 440, 220, 50);

        layout.setBackground(new java.awt.Color(204, 0, 0));
        layout.setForeground(new java.awt.Color(204, 0, 0));
        layout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login page.png"))); // NOI18N
        layout.setText("jLabel2");
        getContentPane().add(layout);
        layout.setBounds(50, 10, 1070, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LOGIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Forgetpwd;
    private javax.swing.JLabel Hoteltap;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Login1;
    private javax.swing.JLabel Mailbox;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel key;
    private javax.swing.JLabel layout;
    private javax.swing.JLabel logo;
    private javax.swing.JButton redbox;
    // End of variables declaration//GEN-END:variables
}
private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {

    String email = txtEmail.getText();
    String password = new String(txtPassword.getPassword());

    LoginController controller = new LoginController();
    User user = controller.authenticate(email, password);

    if (user != null) {
        JOptionPane.showMessageDialog(this, "Login Successful");

        if (user.getRole().equals("ADMIN")) {
            new AdminDashboard().setVisible(true);
        } else {
            new UserDashboard().setVisible(true);
        }
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid Email or Password");
    }
}