/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author hp
 */
public class login extends javax.swing.JFrame {
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form LOGIN
     * @param 
     */
    
    public login() {
        initComponents();
    }
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */ // Call your existing UI setup    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        forgetpassword = new javax.swing.JLabel();
        Mailbox = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        key = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        slogan = new javax.swing.JLabel();
        layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, -10, 100, 90);

        account.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));
        account.setText("Create an account");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        jPanel1.add(account);
        account.setBounds(660, 520, 180, 30);

        forgetpassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        forgetpassword.setForeground(new java.awt.Color(255, 255, 255));
        forgetpassword.setText("Forget password?");
        jPanel1.add(forgetpassword);
        forgetpassword.setBounds(860, 520, 170, 30);

        Mailbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mailbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mailicon.png"))); // NOI18N
        jPanel1.add(Mailbox);
        Mailbox.setBounds(990, 240, 50, 60);

        Login.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(239, 139, 163));
        Login.setText("Login ");
        jPanel1.add(Login);
        Login.setBounds(780, 110, 130, 60);
        jPanel1.add(emailfield);
        emailfield.setBounds(660, 250, 320, 50);
        jPanel1.add(passwordfield);
        passwordfield.setBounds(660, 350, 320, 50);

        key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 1.png"))); // NOI18N
        jPanel1.add(key);
        key.setBounds(990, 350, 40, 40);

        email.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        jPanel1.add(email);
        email.setBounds(660, 220, 120, 30);

        password.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        jPanel1.add(password);
        password.setBounds(660, 320, 120, 30);

        loginbutton.setBackground(new java.awt.Color(184, 12, 47));
        loginbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(239, 139, 163));
        loginbutton.setText("Login");
        loginbutton.setBorder(null);
        loginbutton.addActionListener(this::loginbuttonActionPerformed);
        jPanel1.add(loginbutton);
        loginbutton.setBounds(730, 433, 200, 50);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(90, 36, 90, 20);

        layout.setBackground(new java.awt.Color(204, 0, 0));
        layout.setForeground(new java.awt.Color(204, 0, 0));
        layout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login page.png"))); // NOI18N
        jPanel1.add(layout);
        layout.setBounds(0, 0, 1190, 699);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_accountMouseClicked

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_loginbuttonActionPerformed
    
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Mailbox;
    private javax.swing.JLabel account;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel forgetpassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel key;
    private javax.swing.JLabel layout;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTextField getEmailField() {
        return emailfield; 
    }
    public javax.swing.JPasswordField getPasswordField() { 
        return passwordfield; 
    }
    public javax.swing.JButton getLoginButton() {
    return loginbutton;
}
     public void addLoginButtonListener(java.awt.event.ActionListener listener) {
        loginbutton.addActionListener(listener);
    }
     public javax.swing.JLabel getAccountLabel() {
        return account; // The "Create an account" label
    }
    
    public javax.swing.JLabel getForgotPasswordLabel() {
        return forgetpassword; // The "Forget password?" label
    }
}
