/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nirajhamal
 */

public class logout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(logout.class.getName());

    /**
     * Creates new form support
     */
    public logout

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
<<<<<<<< HEAD:src/view/logout.java
        number3 = new javax.swing.JLabel();
        helpfulbutton = new javax.swing.JButton();
        slogan = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
========
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
>>>>>>>> niraj:src/view/bookingconfirmed.java

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

<<<<<<<< HEAD:src/view/logout.java
        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        number3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        number3.setForeground(new java.awt.Color(255, 255, 255));
        number3.setText("You have been logged out.");
        jPanel1.add(number3);
        number3.setBounds(360, 170, 470, 60);

        helpfulbutton.setBackground(new java.awt.Color(185, 12, 47));
        helpfulbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        helpfulbutton.setForeground(new java.awt.Color(241, 150, 174));
        helpfulbutton.setText("Login");
        helpfulbutton.setBorder(null);
        helpfulbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpfulbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(helpfulbutton);
        helpfulbutton.setBounds(360, 250, 120, 30);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(130, 40, 90, 16);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 1260, 730);
========
        jPanel3.setLayout(null);

        jButton2.setBackground(new java.awt.Color(184, 13, 47));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(241, 151, 174));
        jButton2.setText("PAY NOW");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(530, 520, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/A12BC.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 10, 1140, 17);
>>>>>>>> niraj:src/view/bookingconfirmed.java

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<<< HEAD:src/view/logout.java
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
========
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
>>>>>>>> niraj:src/view/bookingconfirmed.java
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void helpfulbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpfulbuttonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        new login().setVisible(true);
   
    }//GEN-LAST:event_helpfulbuttonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new logout().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton helpfulbutton;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel number3;
    private javax.swing.JLabel slogan;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
>>>>>>>> niraj:src/view/bookingconfirmed.java
    // End of variables declaration//GEN-END:variables
}
