/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.NotificationController;
import model.NotificationModel;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author sailenawale
 */
public class notifications extends javax.swing.JFrame {
    private final int currentUserId = 1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(notifications.class.getName());

    /**
     * Creates new form notifications
     */
    public notifications() {
        initComponents();
        loadNotifications();
        setLocationRelativeTo(null);
    }
private void loadNotifications() {
       try {
        NotificationController controller = new NotificationController();
        List<NotificationModel> notifications = controller.getUserNotifications(currentUserId);
        
        // Use jList1 (your JList component)
        DefaultListModel<String> model = new DefaultListModel<>();
        
        if (notifications.isEmpty()) {
            model.addElement(" No notifications yet");
            model.addElement("Update your profile to get notifications!");
        } else {
            for (NotificationModel notif : notifications) {
                String displayText = "• " + notif.getMessage() + 
                                   " [" + notif.getCreatedAt() + "]";
                model.addElement(displayText);
            }
        }
        
        jList1.setModel(model);
        
    } catch (Exception e) {
        // Show error in the list
        DefaultListModel<String> errorModel = new DefaultListModel<>();
        errorModel.addElement("Error loading notifications");
        errorModel.addElement("Check database connection");
        jList1.setModel(errorModel);
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userdashboard = new javax.swing.JLabel();
        notificationsicon = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        msg1 = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        list = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        backbutton = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        userdashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        userdashboard.setForeground(new java.awt.Color(232, 128, 153));
        userdashboard.setText("Notifications");
        jPanel1.add(userdashboard);
        userdashboard.setBounds(510, 40, 290, 40);

        notificationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notifications.png"))); // NOI18N
        jPanel1.add(notificationsicon);
        notificationsicon.setBounds(420, 40, 50, 40);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(140, 50, 90, 16);

        msg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/msg.png"))); // NOI18N
        jPanel1.add(msg);
        msg.setBounds(320, 350, 40, 40);

        msg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/msg.png"))); // NOI18N
        jPanel1.add(msg1);
        msg1.setBounds(320, 170, 40, 40);

        msg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/msg.png"))); // NOI18N
        jPanel1.add(msg2);
        msg2.setBounds(320, 260, 40, 40);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setViewportView(jList1);

        jPanel1.add(list);
        list.setBounds(380, 170, 560, 450);

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backbutton.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(330, 50, 40, 30);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 1270, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        this.dispose();

        // Open userdashboard
        new userdashboard().setVisible(true);
    }//GEN-LAST:event_backbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new notifications().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JLabel image;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane list;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel notificationsicon;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel userdashboard;
    // End of variables declaration//GEN-END:variables
}
