/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author sailenawale
 */
public class profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(profile.class.getName());
  
 
 
    /**
     * Creates new form profile
     */
   
public profile() {
    initComponents();
     
}
  
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        cancelbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        phoneno = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        mailicon = new javax.swing.JLabel();
        nameicon = new javax.swing.JLabel();
        noicon = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        faceicon = new javax.swing.JLabel();
        idicon = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        newpp = new javax.swing.JLabel();
        uploadbutton = new javax.swing.JButton();
        fullnamefield = new javax.swing.JTextField();
        removebutton = new javax.swing.JButton();
        emailfield = new javax.swing.JTextField();
        phonenofield = new javax.swing.JTextField();
        useridfield = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        profile.setBackground(new java.awt.Color(201, 12, 51));
        profile.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        profile.setForeground(new java.awt.Color(201, 12, 51));
        profile.setText("Profile");
        jPanel1.add(profile);
        profile.setBounds(60, 80, 120, 60);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(120, 40, 90, 16);

        cancelbutton.setBackground(new java.awt.Color(184, 12, 47));
        cancelbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        cancelbutton.setForeground(new java.awt.Color(232, 128, 153));
        cancelbutton.setText("Cancel");
        cancelbutton.setBorder(null);
        cancelbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbuttonMouseClicked(evt);
            }
        });
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbutton);
        cancelbutton.setBounds(630, 430, 110, 30);

        logoutbutton.setBackground(new java.awt.Color(184, 12, 47));
        logoutbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(232, 128, 153));
        logoutbutton.setText("Logout");
        logoutbutton.setBorder(null);
        logoutbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbuttonMouseClicked(evt);
            }
        });
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbutton);
        logoutbutton.setBounds(510, 510, 110, 30);

        editbutton.setBackground(new java.awt.Color(184, 12, 47));
        editbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        editbutton.setForeground(new java.awt.Color(232, 128, 153));
        editbutton.setText("Edit");
        editbutton.setBorder(null);
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(editbutton);
        editbutton.setBounds(380, 433, 110, 30);

        email.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-mail");
        jPanel1.add(email);
        email.setBounds(380, 260, 70, 30);

        phoneno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        phoneno.setForeground(new java.awt.Color(255, 255, 255));
        phoneno.setText("Phone no");
        jPanel1.add(phoneno);
        phoneno.setBounds(380, 330, 90, 30);

        userid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setText("User Id");
        jPanel1.add(userid);
        userid.setBounds(380, 120, 70, 30);

        mailicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 3.png"))); // NOI18N
        jPanel1.add(mailicon);
        mailicon.setBounds(700, 270, 30, 20);

        nameicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 6.png"))); // NOI18N
        jPanel1.add(nameicon);
        nameicon.setBounds(700, 200, 42, 17);

        noicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 7.png"))); // NOI18N
        jPanel1.add(noicon);
        noicon.setBounds(700, 340, 42, 17);

        fullname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setText("Full name");
        jPanel1.add(fullname);
        fullname.setBounds(380, 190, 80, 30);

        faceicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newface.png"))); // NOI18N
        jPanel1.add(faceicon);
        faceicon.setBounds(50, 140, 140, 170);

        idicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-badge.png"))); // NOI18N
        jPanel1.add(idicon);
        idicon.setBounds(700, 120, 42, 30);

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backbutton.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(40, 630, 40, 30);
        jPanel1.add(newpp);
        newpp.setBounds(20, 110, 190, 230);

        uploadbutton.setBackground(new java.awt.Color(184, 12, 47));
        uploadbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        uploadbutton.setForeground(new java.awt.Color(232, 128, 153));
        uploadbutton.setText("Upload ");
        uploadbutton.setBorder(null);
        uploadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(uploadbutton);
        uploadbutton.setBounds(30, 340, 70, 30);
        jPanel1.add(fullnamefield);
        fullnamefield.setBounds(480, 200, 210, 23);

        removebutton.setBackground(new java.awt.Color(184, 12, 47));
        removebutton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        removebutton.setForeground(new java.awt.Color(232, 128, 153));
        removebutton.setText("Remove");
        removebutton.setBorder(null);
        removebutton.setBorderPainted(false);
        removebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(removebutton);
        removebutton.setBounds(130, 340, 70, 30);
        jPanel1.add(emailfield);
        emailfield.setBounds(470, 270, 210, 23);

        phonenofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenofieldActionPerformed(evt);
            }
        });
        jPanel1.add(phonenofield);
        phonenofield.setBounds(480, 340, 210, 23);
        jPanel1.add(useridfield);
        useridfield.setBounds(480, 130, 210, 23);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 1280, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbuttonMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_cancelbuttonMouseClicked

    private void logoutbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbuttonMouseClicked
        
       

    }//GEN-LAST:event_logoutbuttonMouseClicked

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
       
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // TODO add your handling code here:
                                            

    }//GEN-LAST:event_editbuttonActionPerformed

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonMouseClicked

    private void uploadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbuttonActionPerformed
        // TODO add your handling code here:
       
     
    }//GEN-LAST:event_uploadbuttonActionPerformed

    private void removebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebuttonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_removebuttonActionPerformed

    private void phonenofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenofieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton editbutton;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel faceicon;
    private javax.swing.JLabel fullname;
    private javax.swing.JTextField fullnamefield;
    private javax.swing.JLabel idicon;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JLabel mailicon;
    private javax.swing.JLabel nameicon;
    private javax.swing.JLabel newpp;
    private javax.swing.JLabel noicon;
    private javax.swing.JLabel phoneno;
    private javax.swing.JTextField phonenofield;
    private javax.swing.JLabel profile;
    private javax.swing.JButton removebutton;
    private javax.swing.JLabel slogan;
    private javax.swing.JButton uploadbutton;
    private javax.swing.JLabel userid;
    private javax.swing.JTextField useridfield;
    // End of variables declaration//GEN-END:variables
public javax.swing.JTextField getUserIdField() { return useridfield; }
public javax.swing.JTextField getFullNameField() { return fullnamefield; }
public javax.swing.JTextField getEmailField() { return emailfield; }
public javax.swing.JTextField getPhoneField() { return phonenofield; }
public javax.swing.JLabel getPhotoLabel() { return newpp; }
public javax.swing.JButton getEditButton() { return editbutton; }
public javax.swing.JLabel getBackButtonLabel() { return backbutton; }
public javax.swing.JButton getCancelButton() { return cancelbutton; }
public javax.swing.JButton getLogoutButton() { return logoutbutton; }
public javax.swing.JButton getUploadButton() { return uploadbutton; }
public javax.swing.JButton getRemoveButton() { return removebutton; }}
