/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


/**
 *
 * @author sailenawale
 */
public class reviews extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(reviews.class.getName());

    /**
     * Creates new form reviews
     */
    
    public reviews() {
    initComponents(); // This line is CRITICAL
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        reviews = new javax.swing.JLabel();
        addreviewbutton = new javax.swing.JButton();
        viewdetailsbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtreviews = new javax.swing.JTextArea();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(120, 40, 90, 20);

        reviews.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        reviews.setForeground(new java.awt.Color(241, 150, 174));
        reviews.setText("Reviews");
        jPanel1.add(reviews);
        reviews.setBounds(340, 120, 180, 40);

        addreviewbutton.setBackground(new java.awt.Color(184, 12, 47));
        addreviewbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addreviewbutton.setForeground(new java.awt.Color(232, 128, 153));
        addreviewbutton.setText("Add review");
        addreviewbutton.setBorder(null);
        addreviewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addreviewbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addreviewbutton);
        addreviewbutton.setBounds(390, 513, 150, 40);

        viewdetailsbutton.setBackground(new java.awt.Color(184, 12, 47));
        viewdetailsbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        viewdetailsbutton.setForeground(new java.awt.Color(232, 128, 153));
        viewdetailsbutton.setText("View details");
        viewdetailsbutton.setBorder(null);
        jPanel1.add(viewdetailsbutton);
        viewdetailsbutton.setBounds(690, 510, 170, 40);

        jScrollPane1.setForeground(new java.awt.Color(254, 185, 206));

        txtreviews.setEditable(false);
        txtreviews.setBackground(new java.awt.Color(255, 255, 255));
        txtreviews.setColumns(20);
        txtreviews.setFont(new java.awt.Font("Arial Hebrew Scholar", 0, 18)); // NOI18N
        txtreviews.setLineWrap(true);
        txtreviews.setRows(20);
        jScrollPane1.setViewportView(txtreviews);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 170, 600, 420);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 1280, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addreviewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addreviewbuttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addreviewbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new reviews().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addreviewbutton;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reviews;
    private javax.swing.JLabel slogan;
    private javax.swing.JTextArea txtreviews;
    private javax.swing.JButton viewdetailsbutton;
    // End of variables declaration//GEN-END:variables
                                            
    
    // UI Event Listener ONLY
    private void viewdetailsbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Handle view details if needed
    }                                               
    
    // Getter for UI component
    public javax.swing.JTextArea getReviewsTextArea() {
        return txtreviews;
    }}
