/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UserController;
import javax.swing.JOptionPane;




/**
 *
 * @author hp
 */
public class signup extends javax.swing.JFrame {
    private final UserController userController;
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger( signup.class.getName());
   
    /**
     * Creates new form SIGNUP
     */
    public  signup() {
        userController = new UserController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailfield = new javax.swing.JTextField();
        signup = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        logouser = new javax.swing.JLabel();
        mailbox = new javax.swing.JLabel();
        key = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        signupbutton = new javax.swing.JButton();
        usernamefield = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        slogan = new javax.swing.JLabel();
        layout = new javax.swing.JLabel();
        signup2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(emailfield);
        emailfield.setBounds(140, 290, 300, 40);

        signup.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        signup.setForeground(new java.awt.Color(204, 0, 51));
        signup.setText("Sign up");
        getContentPane().add(signup);
        signup.setBounds(240, 80, 180, 70);

        account.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));
        account.setText("Already have an account?");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        getContentPane().add(account);
        account.setBounds(190, 510, 230, 20);

        logouser.setForeground(new java.awt.Color(255, 255, 255));
        logouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/head.png"))); // NOI18N
        getContentPane().add(logouser);
        logouser.setBounds(450, 210, 40, 40);

        mailbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mailicon.png"))); // NOI18N
        getContentPane().add(mailbox);
        mailbox.setBounds(450, 290, 40, 30);

        key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 1.png"))); // NOI18N
        getContentPane().add(key);
        key.setBounds(450, 360, 50, 60);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(0, -30, 100, 110);

        signupbutton.setBackground(new java.awt.Color(204, 0, 0));
        signupbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(239, 139, 163));
        signupbutton.setText("Sign up ");
        signupbutton.setBorder(null);
        signupbutton.addActionListener(this::signupbuttonActionPerformed);
        getContentPane().add(signupbutton);
        signupbutton.setBounds(180, 450, 220, 40);
        getContentPane().add(usernamefield);
        usernamefield.setBounds(140, 210, 300, 40);

        username.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");
        getContentPane().add(username);
        username.setBounds(140, 180, 120, 30);

        password.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        getContentPane().add(password);
        password.setBounds(140, 340, 120, 30);

        email.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        getContentPane().add(email);
        email.setBounds(140, 260, 120, 30);
        getContentPane().add(passwordfield);
        passwordfield.setBounds(140, 370, 300, 40);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        getContentPane().add(slogan);
        slogan.setBounds(90, 30, 90, 16);

        layout.setBackground(new java.awt.Color(255, 0, 51));
        layout.setForeground(new java.awt.Color(255, 0, 0));
        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup page.png"))); // NOI18N
        getContentPane().add(layout);
        layout.setBounds(0, -50, 1270, 760);

        signup2.setText("jTextField1");
        getContentPane().add(signup2);
        signup2.setBounds(200, 470, 210, 30);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        // TODO add your handling code here:
         signupAction();
         
            
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        new login().setVisible(true);
    }//GEN-LAST:event_accountMouseClicked
private void signupAction() {
    String username = usernamefield.getText().trim();
    String email = emailfield.getText().trim();
    String password = new String(passwordfield.getPassword()).trim();
    
    System.out.println("Signup attempt:");
    System.out.println("Username: " + username);
    System.out.println("Email: " + email);
    System.out.println("Password length: " + password.length());
    
    // Validate input
    if (username.isEmpty() || email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!");
        return;
    }
    
    if (!email.contains("@")) {
        JOptionPane.showMessageDialog(this, "Invalid email format!");
        return;
    }
    
    if (password.length() < 4) {
        JOptionPane.showMessageDialog(this, "Password must be at least 4 characters!");
        return;
    }
    
    UserController userController = new UserController();
    boolean success = userController.signup(username, email, password);
    
    if (success) {
        JOptionPane.showMessageDialog(this, "Signup successful!");
        // ONLY dispose and navigate AFTER successful signup
        this.dispose();
        new login().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Signup failed. Email may already exist.");
        //  Don't dispose - keep form open so user can try again
    }
}

   
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new  signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel key;
    private javax.swing.JLabel layout;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logouser;
    private javax.swing.JLabel mailbox;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel signup;
    private javax.swing.JTextField signup2;
    private javax.swing.JButton signupbutton;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
