/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sailenawale
 */
public class support extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(support.class.getName());

    /**
     * Creates new form support
     */
    public support() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        support = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        number1 = new javax.swing.JLabel();
        number2 = new javax.swing.JLabel();
        number3 = new javax.swing.JLabel();
        helpfulbutton = new javax.swing.JButton();
        slogan = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        support.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        support.setForeground(new java.awt.Color(241, 150, 174));
        support.setText("Support");
        jPanel1.add(support);
        support.setBounds(380, 140, 180, 40);

        number.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        number.setForeground(new java.awt.Color(255, 255, 255));
        number.setText("Find us in social media: bookease");
        jPanel1.add(number);
        number.setBounds(380, 380, 300, 30);

        number1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        number1.setForeground(new java.awt.Color(255, 255, 255));
        number1.setText("Phone no: +977 9837256780 ");
        jPanel1.add(number1);
        number1.setBounds(380, 260, 260, 30);

        number2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        number2.setForeground(new java.awt.Color(255, 255, 255));
        number2.setText("Tel no: 5134567");
        jPanel1.add(number2);
        number2.setBounds(380, 300, 260, 30);

        number3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        number3.setForeground(new java.awt.Color(255, 255, 255));
        number3.setText("Email: bookease.org.com");
        jPanel1.add(number3);
        number3.setBounds(380, 340, 260, 30);

        helpfulbutton.setBackground(new java.awt.Color(185, 12, 47));
        helpfulbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        helpfulbutton.setForeground(new java.awt.Color(241, 150, 174));
        helpfulbutton.setText("Helpful");
        helpfulbutton.setBorder(null);
        helpfulbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpfulbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(helpfulbutton);
        helpfulbutton.setBounds(380, 440, 120, 40);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(120, 40, 90, 16);

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backbutton.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(40, 630, 40, 30);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 1260, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpfulbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpfulbuttonMouseClicked
        // TODO add your handling code here:
        
        this.dispose();

        // Open userdashboard
        new userdashboard().setVisible(true);
    
 
    }//GEN-LAST:event_helpfulbuttonMouseClicked

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        this.dispose();

        // Open userdashboard
        new userdashboard().setVisible(true);
    }//GEN-LAST:event_backbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new support().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbutton;
    private javax.swing.JButton helpfulbutton;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel number;
    private javax.swing.JLabel number1;
    private javax.swing.JLabel number2;
    private javax.swing.JLabel number3;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel support;
    // End of variables declaration//GEN-END:variables
}
