/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.*;  // Add this if not already there
import model.Hotel;    
import java.awt.Image; 

// Add this to import your Hotel class
public class userdashboard extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(userdashboard.class.getName());
    
    
    public userdashboard() {
        initComponents();
         drawerPanel.setLocation(-300, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        userdashboard = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        menubar = new javax.swing.JLabel();
        drawerPanel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        bookinghistory = new javax.swing.JLabel();
        notifications = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        notificationsicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        profileicon = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        welcome = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 600, 130, 90);

        userdashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        userdashboard.setForeground(new java.awt.Color(232, 128, 153));
        userdashboard.setText("User Dashboard");
        jPanel1.add(userdashboard);
        userdashboard.setBounds(500, 36, 290, 44);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(100, 636, 90, 50);

        menubar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hamburger Menu.png"))); // NOI18N
        menubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubarMouseClicked(evt);
            }
        });
        jPanel1.add(menubar);
        menubar.setBounds(10, 10, 50, 40);

        drawerPanel.setLayout(null);

        profile.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        drawerPanel.add(profile);
        profile.setBounds(80, 360, 150, 30);

        dashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        drawerPanel.add(dashboard);
        dashboard.setBounds(80, 160, 150, 30);

        bookinghistory.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bookinghistory.setForeground(new java.awt.Color(255, 255, 255));
        bookinghistory.setText("Booking History");
        bookinghistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookinghistoryMouseClicked(evt);
            }
        });
        drawerPanel.add(bookinghistory);
        bookinghistory.setBounds(80, 210, 210, 30);

        notifications.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        notifications.setForeground(new java.awt.Color(255, 255, 255));
        notifications.setText("Notifications");
        notifications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationsMouseClicked(evt);
            }
        });
        drawerPanel.add(notifications);
        notifications.setBounds(80, 260, 150, 30);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        drawerPanel.add(bookingicon);
        bookingicon.setBounds(15, 210, 25, 30);

        support.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("Support");
        support.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supportMouseClicked(evt);
            }
        });
        drawerPanel.add(support);
        support.setBounds(80, 310, 150, 30);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        drawerPanel.add(dashboardicon);
        dashboardicon.setBounds(20, 160, 70, 30);

        notificationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notifications.png"))); // NOI18N
        drawerPanel.add(notificationsicon);
        notificationsicon.setBounds(20, 260, 40, 30);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        drawerPanel.add(supporticon);
        supporticon.setBounds(20, 310, 50, 25);

        profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vector.png"))); // NOI18N
        drawerPanel.add(profileicon);
        profileicon.setBounds(20, 360, 60, 30);

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel.png"))); // NOI18N
        panel.setMinimumSize(new java.awt.Dimension(363, 720));
        panel.setPreferredSize(new java.awt.Dimension(330, 700));
        drawerPanel.add(panel);
        panel.setBounds(0, 0, 340, 750);

        jPanel1.add(drawerPanel);
        drawerPanel.setBounds(0, 0, 340, 720);

        searchbar.setText("search here");
        searchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchbarFocusLost(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        jPanel1.add(searchbar);
        searchbar.setBounds(800, 50, 140, 30);

        welcome.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("To add hotels, search for them above!");
        jPanel1.add(welcome);
        welcome.setBounds(500, 300, 510, 90);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(970, 50, 40, 30);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newdash.png"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(1280, 720));
        image.setMinimumSize(new java.awt.Dimension(1280, 720));
        image.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(image);
        image.setBounds(-18, 0, 1250, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        String hotelName = searchbar.getText().trim();
        
        if (hotelName.isEmpty() || hotelName.equals("search here")) {
            JOptionPane.showMessageDialog(this, "Please enter hotel name!");
            return;
        }
        
        // Get hotel from database
        Hotel hotel = getHotelFromDatabase(hotelName);
        
        if (hotel == null) {
            JOptionPane.showMessageDialog(this, "Hotel '" + hotelName + "' not found!");
            return;
        }
        
        // Show hotel on THIS dashboard
        showHotel(hotel);
        
        // Clear search
        searchbar.setText("");
    
    }//GEN-LAST:event_searchMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
         this.dispose();

        // Open profile
        new profile().setVisible(true);
    }//GEN-LAST:event_profileMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
         this.dispose();

        // Open dashboard
        new userdashboard().setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void bookinghistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookinghistoryMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
        //Open bookinghistory
        new bookinghistory().setVisible(true);
    }//GEN-LAST:event_bookinghistoryMouseClicked

    private void notificationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationsMouseClicked
        // TODO add your handling code here:
        this.dispose();

        // Open notifications
        new notifications().setVisible(true);
    }//GEN-LAST:event_notificationsMouseClicked

    private void supportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportMouseClicked
        // TODO add your handling code here:
        this.dispose();

        // Open support
        new support().setVisible(true);
    }//GEN-LAST:event_supportMouseClicked

    private void menubarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMouseClicked
        // TODO add your handling code here:
        if (drawerPanel.getX() < 0) {
        // Slide IN from left
        drawerPanel.setBounds(0, 0, 300, 720);
    } else {
        // Slide OUT to left
        drawerPanel.setBounds(-300, 0, 300, 720);
    }
    }//GEN-LAST:event_menubarMouseClicked

    private void searchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusGained
        // TODO add your handling code here:
        if(searchbar.getText().equals("search here")){
            searchbar.setText("");
        }
    }//GEN-LAST:event_searchbarFocusGained

    private void searchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusLost
        // TODO add your handling code here:
        if(searchbar.getText().equals("")){
            searchbar.setText("search here");}
    }//GEN-LAST:event_searchbarFocusLost

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchbarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new userdashboard().setVisible(true));
    }
    public void showHotel(Hotel hotel) {
        try {
            if (welcome != null && welcome.isVisible()) {
            welcome.setVisible(false);
        }
            // Create hotel card
            hotelcard card = new hotelcard();
            
            // Set hotel info
            card.setHotelId(String.valueOf(hotel.getHotelId()));
            card.setHotelName(hotel.getHotelName());
            card.setLocation(hotel.getLocation());
            card.setRoomStatus(hotel.getRoomstatus());
            card.setRating(hotel.getRating());
            card.setImage(hotel.getImage()); 
          
            
            card.setVisible(true);  
            // Count existing hotel cards
            int hotelCardCount = 0;
            for (java.awt.Component comp : jPanel1.getComponents()) {
                if (comp instanceof hotelcard) {
                    hotelCardCount++;
                }
            }
            
            // CLOSE side-by-side: 300 width + 10px gap
            int cardWidth = 300;
            int cardHeight = 450;
            int gap = 55; // Small gap between cards
            
            // First card: x=400, Second: x=710, Third: x=1020
            int xPosition = 400 + (hotelCardCount * (cardWidth + gap));
            
            // Set position - SMALLER CARD
            card.setBounds(xPosition, 200, cardWidth, cardHeight);
                  
//            card.setBounds(400, 200, 300, 450);
//            // Add to the main panel
            jPanel1.add(card);
       
            jPanel1.setComponentZOrder(card, 0); // Bring to front
       
    
            // Refresh
            jPanel1.revalidate();
            jPanel1.repaint();
            
            card.repaint();
            // Show message
            JOptionPane.showMessageDialog(this, 
                "✓ " + hotel.getHotelName() + " added to your dashboard!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
                
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error showing hotel!");
        }
    }
 private Hotel getHotelFromDatabase(String hotelName) {
        try {
            // Database connection
            java.sql.Connection conn = java.sql.DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/hotel_booking", 
                "root", 
                "shr7y42007@#"
            );
            
            String sql = "SELECT Hotel_id, Hotel_name, Location, Room_status, Rating, image_path " +
                         "FROM hotels WHERE Hotel_name LIKE ?";
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1, "%" + hotelName + "%");
            
            java.sql.ResultSet rs = pstm.executeQuery();
            
            if (rs.next()) {
                Hotel hotel = new Hotel(
                    rs.getInt("Hotel_id"),
                    rs.getString("Hotel_name"),
                    rs.getString("Location"),
                    rs.getString("Room_status"),
                    rs.getDouble("Rating"),
                    rs.getString("image_path")
                );
                
                rs.close();
                pstm.close();
                conn.close();
                return hotel;
            }
            
            rs.close();
            pstm.close();
            conn.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error!");
        }
      return null;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookinghistory;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JPanel drawerPanel;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menubar;
    private javax.swing.JLabel notifications;
    private javax.swing.JLabel notificationsicon;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileicon;
    private javax.swing.JLabel search;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel support;
    private javax.swing.JLabel supporticon;
    private javax.swing.JLabel userdashboard;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
