/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


public class userdashboard extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(userdashboard.class.getName());
    
    
    public userdashboard() {
        initComponents();
        drawerPanel.setLocation(-300, 0);
        
        new controller.DashboardController().setupUserDashboard(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        userdashboard = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        menuicon = new javax.swing.JLabel();
        drawerPanel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        bookinghistory = new javax.swing.JLabel();
        notifications = new javax.swing.JLabel();
        bookingicon = new javax.swing.JLabel();
        support = new javax.swing.JLabel();
        dashboardicon = new javax.swing.JLabel();
        notificationsicon = new javax.swing.JLabel();
        supporticon = new javax.swing.JLabel();
        profileicon = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        welcome = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 600, 130, 90);

        userdashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        userdashboard.setForeground(new java.awt.Color(232, 128, 153));
        userdashboard.setText("User Dashboard");
        jPanel1.add(userdashboard);
        userdashboard.setBounds(500, 36, 290, 45);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(90, 640, 90, 50);

        menuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hamburger Menu.png"))); // NOI18N
        menuicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuiconMouseClicked(evt);
            }
        });
        jPanel1.add(menuicon);
        menuicon.setBounds(10, 10, 50, 40);

        drawerPanel.setLayout(null);

        profile.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        drawerPanel.add(profile);
        profile.setBounds(80, 360, 150, 30);

        dashboard.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        drawerPanel.add(dashboard);
        dashboard.setBounds(80, 160, 150, 30);

        bookinghistory.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        bookinghistory.setForeground(new java.awt.Color(255, 255, 255));
        bookinghistory.setText("Booking History");
        bookinghistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookinghistoryMouseClicked(evt);
            }
        });
        drawerPanel.add(bookinghistory);
        bookinghistory.setBounds(80, 210, 210, 30);

        notifications.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        notifications.setForeground(new java.awt.Color(255, 255, 255));
        notifications.setText("Notifications");
        notifications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationsMouseClicked(evt);
            }
        });
        drawerPanel.add(notifications);
        notifications.setBounds(80, 260, 150, 30);

        bookingicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        drawerPanel.add(bookingicon);
        bookingicon.setBounds(15, 210, 25, 30);

        support.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        support.setForeground(new java.awt.Color(255, 255, 255));
        support.setText("Support");
        support.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supportMouseClicked(evt);
            }
        });
        drawerPanel.add(support);
        support.setBounds(80, 310, 150, 30);

        dashboardicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/=.png"))); // NOI18N
        drawerPanel.add(dashboardicon);
        dashboardicon.setBounds(20, 160, 70, 30);

        notificationsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notifications.png"))); // NOI18N
        drawerPanel.add(notificationsicon);
        notificationsicon.setBounds(20, 260, 40, 30);

        supporticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Support.png"))); // NOI18N
        drawerPanel.add(supporticon);
        supporticon.setBounds(20, 300, 50, 50);

        profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 6.png"))); // NOI18N
        drawerPanel.add(profileicon);
        profileicon.setBounds(20, 350, 80, 50);

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel.png"))); // NOI18N
        panel.setMinimumSize(new java.awt.Dimension(363, 720));
        panel.setPreferredSize(new java.awt.Dimension(330, 700));
        drawerPanel.add(panel);
        panel.setBounds(0, 0, 340, 720);

        jPanel1.add(drawerPanel);
        drawerPanel.setBounds(0, 0, 340, 720);

        searchbar.setBackground(new java.awt.Color(232, 128, 153));
        searchbar.setForeground(new java.awt.Color(255, 255, 255));
        searchbar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchbar.setText("Search here");
        searchbar.setBorder(null);
        searchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchbarFocusLost(evt);
            }
        });
        jPanel1.add(searchbar);
        searchbar.setBounds(800, 40, 140, 40);

        welcome.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("To add hotels, search for them above!");
        jPanel1.add(welcome);
        welcome.setBounds(500, 300, 510, 90);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(970, 50, 40, 30);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newdash.png"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(1280, 720));
        image.setMinimumSize(new java.awt.Dimension(1280, 720));
        image.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(image);
        image.setBounds(0, 0, 1250, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked

    }//GEN-LAST:event_searchMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
      
    }//GEN-LAST:event_profileMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        
    }//GEN-LAST:event_dashboardMouseClicked

    private void bookinghistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookinghistoryMouseClicked
        
    }//GEN-LAST:event_bookinghistoryMouseClicked

    private void notificationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationsMouseClicked
        
    }//GEN-LAST:event_notificationsMouseClicked

    private void supportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportMouseClicked
        
    }//GEN-LAST:event_supportMouseClicked

    private void searchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusGained
        // TODO add your handling code here:
        if(searchbar.getText().trim().equals("Search here")){
            searchbar.setText("");
        }
    }//GEN-LAST:event_searchbarFocusGained

    private void searchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusLost
        // TODO add your handling code here:
        if(searchbar.getText().trim().equals("")){
            searchbar.setText("       Search here");}
    }//GEN-LAST:event_searchbarFocusLost
  
   

    private void menuiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuiconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuiconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new userdashboard().setVisible(true));
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookinghistory;
    private javax.swing.JLabel bookingicon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardicon;
    private javax.swing.JPanel drawerPanel;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuicon;
    private javax.swing.JLabel notifications;
    private javax.swing.JLabel notificationsicon;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileicon;
    private javax.swing.JLabel search;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel support;
    private javax.swing.JLabel supporticon;
    private javax.swing.JLabel userdashboard;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTextField getSearchBar() { return searchbar; }
    public javax.swing.JLabel getSearchButton() { return search; }
    public javax.swing.JPanel getMainPanel() { return jPanel1; }
    public javax.swing.JLabel getWelcomeLabel() { return welcome; }
    public javax.swing.JPanel getDrawerPanel() { return drawerPanel; }
    public javax.swing.JLabel getMenuIcon() { return menuicon; }  
    
    // Navigation getters
    public javax.swing.JLabel getProfileLabel() { return profile; }
    public javax.swing.JLabel getDashboardLabel() { return dashboard; }
    public javax.swing.JLabel getBookingHistoryLabel() { return bookinghistory; }
    public javax.swing.JLabel getNotificationsLabel() { return notifications; }
    public javax.swing.JLabel getSupportLabel() { return support; }
    
    public void addMenuIconListener(java.awt.event.MouseListener listener) {
        menuicon.addMouseListener(listener);
    }
    
}