/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author nirajhamal
 */
public class viewdetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewdetails.class.getName());

    /**
     * Creates new form viewdetails
     */
    public viewdetails() {
        initComponents();
        new controller.ViewdetailsController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        viewdetails = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        hotelid = new javax.swing.JLabel();
        availabilitygooglemaps = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        ratings = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        booknowbutton = new javax.swing.JButton();
        slogan = new javax.swing.JLabel();
        reviews = new javax.swing.JButton();
        hotelname = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        backimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);
        jPanel1.add(image);
        image.setBounds(90, 50, 490, 640);

        viewdetails.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        viewdetails.setForeground(new java.awt.Color(240, 150, 174));
        viewdetails.setText("View Details");
        jPanel1.add(viewdetails);
        viewdetails.setBounds(730, 90, 240, 40);

        location.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setText("Location: ");
        jPanel1.add(location);
        location.setBounds(640, 290, 380, 23);

        hotelid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotelid.setForeground(new java.awt.Color(255, 255, 255));
        hotelid.setText("Hotel id:");
        jPanel1.add(hotelid);
        hotelid.setBounds(640, 190, 370, 23);

        availabilitygooglemaps.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        availabilitygooglemaps.setForeground(new java.awt.Color(255, 255, 255));
        availabilitygooglemaps.setText("Availability in google maps: ");
        jPanel1.add(availabilitygooglemaps);
        availabilitygooglemaps.setBounds(640, 340, 390, 23);

        contact.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setText("Contact: ");
        jPanel1.add(contact);
        contact.setBounds(640, 390, 370, 23);

        price.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Price: ");
        jPanel1.add(price);
        price.setBounds(640, 440, 380, 23);

        ratings.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ratings.setForeground(new java.awt.Color(255, 255, 255));
        ratings.setText("Ratings: ");
        jPanel1.add(ratings);
        ratings.setBounds(640, 490, 380, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adsT 2.png"))); // NOI18N
        logo.setText("jLabel10");
        jPanel1.add(logo);
        logo.setBounds(0, -20, 90, 100);

        booknowbutton.setBackground(new java.awt.Color(184, 13, 47));
        booknowbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        booknowbutton.setForeground(new java.awt.Color(241, 151, 174));
        booknowbutton.setText("Book Now");
        booknowbutton.setBorder(null);
        booknowbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirect_bookingconfirmed(evt);
            }
        });
        jPanel1.add(booknowbutton);
        booknowbutton.setBounds(640, 540, 150, 40);

        slogan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        slogan.setText("Hotel in a tap");
        jPanel1.add(slogan);
        slogan.setBounds(90, 10, 90, 60);

        reviews.setBackground(new java.awt.Color(184, 13, 47));
        reviews.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        reviews.setForeground(new java.awt.Color(241, 151, 174));
        reviews.setText("Reviews");
        reviews.setBorder(null);
        reviews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewsredirect_bookingconfirmed(evt);
            }
        });
        jPanel1.add(reviews);
        reviews.setBounds(860, 540, 150, 40);

        hotelname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotelname.setForeground(new java.awt.Color(255, 255, 255));
        hotelname.setText("Hotel Name:");
        jPanel1.add(hotelname);
        hotelname.setBounds(640, 240, 370, 23);

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backbutton.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(backbutton);
        backbutton.setBounds(40, 650, 40, 30);

        backimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/details.png"))); // NOI18N
        backimg.setText("jLabel1");
        jPanel1.add(backimg);
        backimg.setBounds(0, 0, 1140, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redirect_bookingconfirmed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redirect_bookingconfirmed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_redirect_bookingconfirmed

    private void reviewsredirect_bookingconfirmed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewsredirect_bookingconfirmed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewsredirect_bookingconfirmed

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewdetails().setVisible(true));
    }
    // In viewdetails.java - Add these public setter methods:


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilitygooglemaps;
    private javax.swing.JLabel backbutton;
    private javax.swing.JLabel backimg;
    private javax.swing.JButton booknowbutton;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel hotelid;
    private javax.swing.JLabel hotelname;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel location;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel price;
    private javax.swing.JLabel ratings;
    private javax.swing.JButton reviews;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel viewdetails;
    // End of variables declaration//GEN-END:variables
public javax.swing.JLabel getHotelNameLabel() {
        return hotelname;
    }
    public javax.swing.JLabel getHotelIdLabel() {
        return hotelid;
    }
    public javax.swing.JLabel getLocationLabel() {
        return location;
    }
    
    public javax.swing.JLabel getGoogleMapsLabel() {
        return availabilitygooglemaps;
    }
    
    public javax.swing.JLabel getContactLabel() {
        return contact;
    }
    
    public javax.swing.JLabel getPriceLabel() {
        return price;
    }
    
    public javax.swing.JLabel getRatingsLabel() {
        return ratings;
    }
    
    public javax.swing.JLabel getImageLabel() {
        return image;
    }
    
    public javax.swing.JButton getBookNowButton() {
        return booknowbutton;
    }
    
    public javax.swing.JButton getReviewsButton() {
        return reviews;
    }
public javax.swing.JLabel getBackButton() {
        return backbutton;
    }}
